// frontend/src/app/fichas-clinica/page.tsx
'use client';
import './styles.css';

import React, {ChangeEvent, FormEvent, useEffect, useState} from 'react';
import {apiService} from '@/services/ApiService';
import {useAuth} from '@/components/AuthContext';

interface FichaClinica {
    id_ficha_control: number;
    fecha_control: string;
    observacion: string;
    id_paciente: number;
    id_programa_control: number;
    id_centro_salud: number;
    id_usuario_responsable: number;
}

interface Paciente {
    id_paciente: number;
    rut: string;
    nombre: string;
    apellido_paterno: string;
    apellido_materno: string;
}

interface Programa {
    id_programa_control: number;
    codigo: string;
    nombre: string;
}

interface CentroSalud {
    id_centro_salud: number;
    nombre: string;
}

export default function FichasClinicaPage() {
    const {user} = useAuth();
    const [fichas, setFichas] = useState<FichaClinica[]>([]);
    const [centros, setCentros] = useState<CentroSalud[]>([]);
    const [pacientes, setPacientes] = useState<Paciente[]>([]);
    const [programas, setProgramas] = useState<Programa[]>([]);
    const [form, setForm] = useState({
        fecha_control: '',
        observacion: '',
        id_paciente: '',
        id_programa_control: '',
        id_centro_salud: '',
    });

    useEffect(() => {
        apiService.getFichasControl()
            .then((data) => setFichas(data))
            .catch((err) => console.error('ApiService fichas GET error:', err));

        apiService.getCentrosSalud()
            .then((data) => setCentros(data))
            .catch(() => alert('Error al cargar centros de salud'));

        apiService.getPacientes()
            .then((data) => setPacientes(data))
            .catch(() => alert('Error al cargar pacientes'));

        apiService.getProgramaControl()
            .then((data) => setProgramas(data))
            .catch(() => alert('Error al cargar programas de control'));
    }, []);

    const handleChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setForm({...form, [e.target.name]: e.target.value});
    };

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        if (!user) return;
        const payload = {
            fecha_control: form.fecha_control,
            observacion: form.observacion,
            id_paciente: Number(form.id_paciente),
            id_programa_control: Number(form.id_programa_control),
            id_centro_salud: Number(form.id_centro_salud),
            id_usuario_responsable: user.id,
        };
        try {
            const nueva: FichaClinica = await apiService.createFichaControl(payload);
            setFichas([...fichas, nueva]);
            setForm({
                fecha_control: '',
                observacion: '',
                id_paciente: '',
                id_programa_control: '',
                id_centro_salud: '',
            });
        } catch (err) {
            console.error('ApiService fichas POST error:', err);
        }
    };

    if (!pacientes.length || !programas.length || !centros.length) {
        return <div>Cargando datos...</div>;
    }

    return (
        <div>
            <h1>Fichas Clínicas</h1>
            <form
                onSubmit={handleSubmit}
                className="fichas-form"
            >
                <input
                    name="fecha_control"
                    type="date"
                    placeholder="Fecha Control"
                    value={form.fecha_control}
                    onChange={handleChange}
                    required
                    className="fichas-input-fecha"
                />
                <input
                    name="observacion"
                    placeholder="Observación"
                    value={form.observacion}
                    onChange={handleChange}
                    required
                    className="fichas-input-observacion"
                />
                <select
                    name="id_paciente"
                    value={form.id_paciente}
                    onChange={handleChange}
                    required
                    className="fichas-select-paciente"
                >
                    <option value="">Selecciona paciente</option>
                    {pacientes.map((p) => (
                        <option
                            key={`paciente-${p.id_paciente}`}
                            value={p.id_paciente}
                        >
                            {`${p.rut}, ${p.nombre} ${p.apellido_paterno} ${p.apellido_materno}`}
                        </option>
                    ))}
                </select>
                <select
                    name="id_programa_control"
                    value={form.id_programa_control}
                    onChange={handleChange}
                    required
                    className="fichas-select-programa"
                >
                    <option value="">Selecciona programa</option>
                    {programas.map((pr) => (
                        <option
                            key={`programa-${pr.id_programa_control}`}
                            value={pr.id_programa_control}
                        >
                            {`${pr.codigo}, ${pr.nombre}`}
                        </option>
                    ))}
                </select>
                <select
                    name="id_centro_salud"
                    value={form.id_centro_salud}
                    onChange={handleChange}
                    required
                    className="fichas-select-centro"
                >
                    <option value="">Selecciona centro de salud</option>
                    {centros.map((c) => (
                        <option
                            key={`centro-${c.id_centro_salud}`}
                            value={c.id_centro_salud}
                        >
                            {c.nombre}
                        </option>
                    ))}
                </select>
                <button type="submit" className="fichas-btn">
                    Agregar
                </button>
            </form>

            <table className="fichas-table">
                <thead>
                <tr>
                    <th className="fichas-th">ID</th>
                    <th className="fichas-th">Fecha Control</th>
                    <th className="fichas-th">Observación</th>
                    <th className="fichas-th">Paciente</th>
                    <th className="fichas-th">Programa</th>
                    <th className="fichas-th">Centro Salud</th>
                    <th className="fichas-th">Usuario Resp.</th>
                </tr>
                </thead>
                <tbody>
                {fichas.map((f) => {
                    const paciente = pacientes.find(
                        (p) => Number(p.id_paciente) === Number(f.id_paciente)
                    );
                    const programa = programas.find(
                        (pr) => Number(pr.id_programa_control) === Number(f.id_programa_control)
                    );
                    const centro = centros.find(
                        (c) => Number(c.id_centro_salud) === Number(f.id_centro_salud)
                    );
                    return (
                        <tr key={f.id_ficha_control}>
                            <td className="fichas-td">{f.id_ficha_control}</td>
                            <td className="fichas-td">{new Date(f.fecha_control).toLocaleDateString('es-CL')}</td>
                            <td className="fichas-td">{f.observacion}</td>
                            <td className="fichas-td">
                                {paciente
                                    ? `${paciente.nombre} ${paciente.apellido_paterno} ${paciente.apellido_materno}`
                                    : f.id_paciente}
                            </td>
                            <td className="fichas-td">
                                {programa
                                    ? `${programa.nombre}`
                                    : f.id_programa_control}
                            </td>
                            <td className="fichas-td">{centro ? centro.nombre : f.id_centro_salud}</td>
                            <td className="fichas-td">{user?.nombre ?? f.id_usuario_responsable}</td>
                        </tr>
                    );
                })}
                </tbody>
            </table>
        </div>
    );
}

// frontend/src/app/fichas-clinica/fichas-clinica.component.ts

import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { FichasClinicaDataService } from '../data-services/fichas-clinica-data.service';
import { FichaClinica } from './fichas-clinica.interfaces';

@Component({
  selector: 'app-fichas-clinica',
  standalone: false,
  templateUrl: './fichas-clinica.component.html',
  styleUrl: './fichas-clinica.component.css'
})
export class FichasClinicaComponent implements OnInit {
  fichasClinicas: FichaClinica[] = [];
  loading = true;
  editingFicha: FichaClinica | null = null;
  showModal = false;

  constructor(
    private apiService: ApiService,
    private fichasClinicaDataService: FichasClinicaDataService
  ) { }

  ngOnInit(): void {
    this.loadAllData();
  }

  async loadAllData(): Promise<void> {
    try {
      await this.fichasClinicaDataService.loadStaticData();
      this.fichasClinicas = await this.apiService.getFichasControl();
      this.loading = false;
    } catch (error) {
      console.error('Error al cargar datos:', error);
      this.loading = false;
    }
  }

  openCreateModal(): void {
    this.editingFicha = null;
    this.showModal = true;
  }

  openEditModal(ficha: FichaClinica): void {
    this.editingFicha = ficha;
    this.showModal = true;
  }

  closeModal(): void {
    this.editingFicha = null;
    this.showModal = false;
  }

  async saveFicha(ficha: FichaClinica) {
    await this.apiService.createFichaControl(ficha);
    alert('Ficha clínica creada correctamente');
    await this.loadAllData();
    this.closeModal();
  }

  async updateFicha(ficha: FichaClinica) {
    await this.apiService.updateFichaControl(ficha.id_ficha_control, ficha);
    alert('Ficha clínica actualizada correctamente');
    await this.loadAllData();
    this.closeModal();
  }

  getPacienteNombre(id_paciente: number): string {
    return this.fichasClinicaDataService.getPacienteNombre(id_paciente);
  }

  getProgramaNombre(id_programa: number): string {
    return this.fichasClinicaDataService.getProgramaNombre(id_programa);
  }

  getCentroNombre(id_centro: number): string {
    return this.fichasClinicaDataService.getCentroNombre(id_centro);
  }

  getUsuarioNombre(id_usuario: number): string {
    return this.fichasClinicaDataService.getUsuarioNombre(id_usuario);
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString('es-CL');
  }
}

<div *ngIf="loading">Cargando datos...</div>

<div *ngIf="!loading" class="p-6">
    <table class="table-unified">
        <thead>
            <tr>
                <th class="table-unified-th">ID</th>
                <th class="table-unified-th">Fecha Control</th>
                <th class="table-unified-th">Observación</th>
                <th class="table-unified-th">Paciente</th>
                <th class="table-unified-th">Programa</th>
                <th class="table-unified-th">Centro Salud</th>
                <th class="table-unified-th">Usuario Resp.</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let ficha of fichasClinicas">
                <td class="table-unified-td">{{ ficha.id_ficha_control }}</td>
                <td class="table-unified-td">{{ formatDate(ficha.fecha_control) }}</td>
                <td class="table-unified-td">{{ ficha.observacion }}</td>
                <td class="table-unified-td">{{ getPacienteNombre(ficha.id_paciente) }}</td>
                <td class="table-unified-td">{{ getProgramaNombre(ficha.id_programa_control) }}</td>
                <td class="table-unified-td">{{ getCentroNombre(ficha.id_centro_salud) }}</td>
                <td class="table-unified-td">{{ getUsuarioNombre(ficha.id_usuario_responsable) }}</td>
            </tr>
        </tbody>
    </table>

    <div *ngIf="fichasClinicas.length === 0" class="text-center py-8 text-gray-500">
        No hay fichas clínicas registradas
    </div>
</div>
