// frontend/src/app/pacientes/page.tsx
'use client';
import './styles.css';

import React, {useEffect, useState} from "react";
import PacienteForm from "./PacienteForm";
import {apiService} from "@/services/ApiService";

interface Paciente {
    id_paciente: number;
    nombre: string;
    rut: string;
    fecha_nacimiento: string;
    direccion: string;
    apellido_paterno: string;
    apellido_materno: string;
    genero: string;
    telefono: string;
}

const capitalizeWords = (str: string) =>
    str.replace(/\b\w+/g, (w) => w[0].toUpperCase() + w.slice(1).toLowerCase());

export default function Page() {
    const [pacientes, setPacientes] = useState<Paciente[]>([]);
    const [error, setError] = useState<string | null>(null);
    const [editingPaciente, setEditingPaciente] = useState<Paciente | null>(null);
    const [showForm, setShowForm] = useState(false);
    const [search, setSearch] = useState("");

    // Filtrado profesional y minimalista
    const filteredPacientes = pacientes.filter((p) => {
        const q = search.trim().toLowerCase();
        if (!q) return true;
        return (
            p.nombre.toLowerCase().includes(q) ||
            p.apellido_paterno.toLowerCase().includes(q) ||
            p.apellido_materno.toLowerCase().includes(q) ||
            p.rut.toLowerCase().includes(q) ||
            p.telefono.toLowerCase().includes(q) ||
            p.direccion.toLowerCase().includes(q)
        );
    });

    const fetchPacientes = async () => {
        try {
            const data = await apiService.getPacientes();
            setPacientes(data);
            setError(null);
        } catch (err: any) {
            setError(err?.message || "Error desconocido");
            setPacientes([]);
        }
    };

    useEffect(() => {
        fetchPacientes();
    }, []);

    const handleEdit = (paciente: Paciente) => {
        setEditingPaciente(paciente);
        setShowForm(true);
    };

    const handleDelete = async (id: number) => {
        if (!confirm("¿Seguro que deseas eliminar este paciente?")) return;
        try {
            await apiService.deletePaciente(id);
            setPacientes((prev) => prev.filter((p) => p.id_paciente !== id));
        } catch (err: any) {
            setError(err.message);
        }
    };

    const handleFormClose = (updated?: boolean) => {
        setEditingPaciente(null);
        setShowForm(false);
        if (updated) fetchPacientes();
    };

    return (
        <main className="pacientes-main">
            <div
                className="patients-header"
            >
                <h1 className="patients-header-title">Pacientes</h1>
                <div
                    className="patients-header-search"
                >
                    <input
                        type="text"
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        placeholder="Buscar paciente"
                        className="patients-search-input"
                        autoComplete="off"
                    />
                    <div className="patients-total">
                        Total: {filteredPacientes.length}
                    </div>
                </div>
            </div>
            <button
                className="add-patient-btn"
                onClick={() => {
                    setEditingPaciente(null);
                    setShowForm(true);
                }}
            >
                {" "}
                Agregar Paciente{" "}
            </button>
            <PacienteForm
                paciente={editingPaciente}
                show={showForm}
                onClose={handleFormClose}
            />
            {error ? (
                <div className="pacientes-error">
                    <h2 className="pacientes-error-title">
                        ⚠️ Error cargando pacientes
                    </h2>
                    <p>{error}</p>
                </div>
            ) : (
                <div className="pacientes-list">
                    {filteredPacientes.length > 0 ? (
                        filteredPacientes.map((p) => {
                            const initials = `${p.nombre?.[0] || ""}${p.apellido_paterno?.[0] || ""
                            }`.toUpperCase();
                            return (
                                <div
                                    key={p.id_paciente}
                                    className="patient-card patient-card-list"
                                >
                                    <div
                                        className="patient-avatar"
                                        title={`Avatar de ${p.nombre}`}
                                    >
                                        {initials}
                                    </div>
                                    <div className="patient-info-list">
                                        <h3>
                                            {capitalizeWords(p.nombre)}{" "}
                                            {capitalizeWords(p.apellido_paterno)}{" "}
                                            {capitalizeWords(p.apellido_materno)}
                                        </h3>
                                        <div
                                            className="patient-meta-list"
                                        >
                                            <p>
                                                <strong>RUT:</strong> {p.rut}
                                            </p>
                                            <p>
                                                <strong>F. Nac.:</strong>{" "}
                                                {new Date(p.fecha_nacimiento).toLocaleDateString(
                                                    "es-CL"
                                                )}
                                            </p>
                                            <p>
                                                <strong>Género:</strong> {capitalizeWords(p.genero)}
                                            </p>
                                            <p>
                                                <strong>Teléfono:</strong> {p.telefono}
                                            </p>
                                            <p>
                                                <strong>Dirección:</strong>{" "}
                                                {capitalizeWords(p.direccion)}
                                            </p>
                                        </div>
                                    </div>
                                    <div
                                        className="patient-actions patient-actions-list"
                                    >
                                        <button onClick={() => handleEdit(p)}>Editar</button>
                                        <button
                                            onClick={() => handleDelete(p.id_paciente)}
                                        >
                                            Eliminar
                                        </button>
                                    </div>
                                </div>
                            );
                        })
                    ) : (
                        <div className="empty-state">
                            <h3>No hay pacientes registrados</h3>
                            <p>
                                Comienza agregando tu primer paciente usando el botón de arriba
                            </p>
                        </div>
                    )}
                </div>
            )}
        </main>
    );
}

// frontend/src/app/pacientes/pacientes.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { PacientesDataService } from '../data-services/pacientes-data.service';
import { Paciente } from './pacientes.interfaces';

@Component({
    selector: 'app-pacientes',
    standalone: false,
    templateUrl: './pacientes.component.html',
    styleUrls: ['./pacientes.component.css']
})
export class PacientesComponent implements OnInit {
    pacientes: Paciente[] = [];
    error: string | null = null;
    editingPaciente: Paciente | null = null;
    showForm = false;
    search = '';
    loading = false;

    constructor(
        private apiService: ApiService,
        private pacientesDataService: PacientesDataService
    ) { }

    async ngOnInit(): Promise<void> {
        await this.loadAllData();
    }

    async loadAllData(): Promise<void> {
        try {
            this.loading = true;

            // ✅ OPTIMIZACIÓN: Cargar datos principales Y estáticos EN PARALELO
            const [pacientesData] = await Promise.all([
                this.apiService.getPacientes(),
                this.pacientesDataService.loadStaticData() // Se ejecuta en paralelo, no bloquea
            ]);

            // Mostrar los pacientes inmediatamente
            this.pacientes = pacientesData;
            this.loading = false;
        } catch (error) {
            console.error('❌ [PacientesComponent] Error al cargar datos:', error);
            this.loading = false;
            this.error = 'Error al cargar los pacientes';
            // En caso de error, mostrar array vacío
            this.pacientes = [];
        }
    }

    get filteredPacientes(): Paciente[] {
        const q = this.search.trim().toLowerCase();
        if (!q) return this.pacientes;

        return this.pacientes.filter(p =>
            p.nombre.toLowerCase().includes(q) ||
            p.apellido_paterno.toLowerCase().includes(q) ||
            p.apellido_materno.toLowerCase().includes(q) ||
            p.rut.toLowerCase().includes(q) ||
            p.telefono.toLowerCase().includes(q) ||
            p.direccion.toLowerCase().includes(q)
        );
    }

    handleEdit(paciente: Paciente): void {
        this.editingPaciente = paciente;
        this.showForm = true;
    }

    openForm(): void {
        this.editingPaciente = null;
        this.showForm = true;
    }

    onFormClose(updated: boolean = false): void {
        this.editingPaciente = null;
        this.showForm = false;
        if (updated) {
            this.loadAllData();
        }
    }

    async handleDelete(id: number): Promise<void> {
        if (!confirm('¿Seguro que deseas eliminar este paciente?')) return;

        try {
            await this.apiService.deletePaciente(id);
            this.pacientes = this.pacientes.filter(p => p.id_paciente !== id);
        } catch (err: any) {
            this.error = err.message;
        }
    }

    capitalizeWords(str: string): string {
        return str.replace(/\b\w+/g, (w) => w[0].toUpperCase() + w.slice(1).toLowerCase());
    }

    getInitials(paciente: Paciente): string {
        return `${paciente.nombre?.[0] || ''}${paciente.apellido_paterno?.[0] || ''}`.toUpperCase();
    }

    formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('es-CL');
    }
}

<div class="pacientes-main">
    <div class="patients-header">
        <h1 class="patients-header-title">Pacientes</h1>
        <div class="patients-header-search">
            <input type="text" [(ngModel)]="search" placeholder="Buscar paciente" class="patients-search-input"
                autocomplete="off" />
            <div class="patients-total">
                Total: {{ filteredPacientes.length }}
            </div>
        </div>
    </div>

    <button class="add-patient-btn" (click)="openForm()">
        Agregar Paciente
    </button>

    <app-paciente-form [paciente]="editingPaciente" [show]="showForm" (close)="onFormClose($event)">
    </app-paciente-form>

    <div *ngIf="error" class="pacientes-error">
        <h2 class="pacientes-error-title">⚠️ Error cargando pacientes</h2>
        <p>{{ error }}</p>
    </div>

    <div *ngIf="!error" class="pacientes-list">
        <div *ngIf="filteredPacientes.length > 0; else emptyState">
            <div *ngFor="let p of filteredPacientes" class="patient-card patient-card-list">
                <div class="patient-avatar" [title]="'Avatar de ' + p.nombre">
                    {{ getInitials(p) }}
                </div>
                <div class="patient-info-list">
                    <h3>
                        {{ capitalizeWords(p.nombre) }}
                        {{ capitalizeWords(p.apellido_paterno) }}
                        {{ capitalizeWords(p.apellido_materno) }}
                    </h3>
                    <div class="patient-meta-list">
                        <p><strong>RUT:</strong> {{ p.rut }}</p>
                        <p><strong>F. Nac.:</strong> {{ formatDate(p.fecha_nacimiento) }}</p>
                        <p><strong>Género:</strong> {{ capitalizeWords(p.genero) }}</p>
                        <p><strong>Teléfono:</strong> {{ p.telefono }}</p>
                        <p><strong>Dirección:</strong> {{ capitalizeWords(p.direccion) }}</p>
                    </div>
                </div>
                <div class="patient-actions patient-actions-list">
                    <button (click)="handleEdit(p)">Editar</button>
                    <button (click)="handleDelete(p.id_paciente)">Eliminar</button>
                </div>
            </div>
        </div>

        <ng-template #emptyState>
            <div class="empty-state">
                <h3>No hay pacientes registrados</h3>
                <p>Comienza agregando tu primer paciente usando el botón de arriba</p>
            </div>
        </ng-template>
    </div>
</div>
