// frontend/src/app/fichas-odontologica/page.tsx
'use client';
import './styles.css';

import React, {ChangeEvent, FormEvent, useEffect, useState} from 'react';
import {apiService} from '@/services/ApiService';
import {useAuth} from '@/components/AuthContext';

interface FichaOdontologica {
    id_ficha_odontologica: number;
    fecha_control: string;
    observacion: string;
    id_paciente: number;
    id_programa_salud_oral: number;
    id_centro_salud: number;
    id_usuario_responsable: number;
}

interface Paciente {
    id_paciente: number;
    rut: string;
    nombre: string;
    apellido_paterno: string;
    apellido_materno: string;
}

interface ProgramaSaludOral {
    id_programa_salud_oral: number;
    codigo: string;
    nombre: string;
}

interface CentroSalud {
    id_centro_salud: number;
    nombre: string;
}

export default function FichasOdontologicaPage() {
    const {user} = useAuth();
    const [fichas, setFichas] = useState<FichaOdontologica[]>([]);
    const [pacientes, setPacientes] = useState<Paciente[]>([]);
    const [programas, setProgramas] = useState<ProgramaSaludOral[]>([]);
    const [centros, setCentros] = useState<CentroSalud[]>([]);
    const [form, setForm] = useState({
        fecha_control: '',
        observacion: '',
        id_paciente: '',
        id_programa_salud_oral: '',
        id_centro_salud: '',
    });

    useEffect(() => {
        apiService.getFichasControl()
            .then((data) => setFichas(data)) // Ya no es necesario '|| []'
            .catch((err) => console.error('ApiService fichas GET error:', err));

        apiService.getCentrosSalud()
            .then((data) => setCentros(data)) // Valida respuesta de API
            .catch(() => alert('Error al cargar centros de salud'));

        apiService.getPacientes()
            .then((data) => setPacientes(data)) // Valida respuesta de API
            .catch(() => alert('Error al cargar pacientes'));

        apiService.getProgramasSaludOral()
            .then((data) => setProgramas(data)) // Valida respuesta de API
            .catch(() => alert('Error al cargar programas de control'));
    }, []);

    const handleChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        setForm({...form, [e.target.name]: e.target.value});
    };

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        if (!user) return;
        const payload = {
            fecha_control: form.fecha_control,
            observacion: form.observacion,
            id_paciente: Number(form.id_paciente),
            id_programa_salud_oral: Number(form.id_programa_salud_oral),
            id_centro_salud: Number(form.id_centro_salud),
            id_usuario_responsable: user.id,
        };
        try {
            const nueva: FichaOdontologica = await apiService.createFichaOdonto(payload);
            setFichas([...fichas, nueva]);
            setForm({
                fecha_control: '',
                observacion: '',
                id_paciente: '',
                id_programa_salud_oral: '',
                id_centro_salud: '',
            });
        } catch (err: any) {
            alert('Error al crear ficha odontológica' + err.message);
        }
    };

    if (!pacientes.length || !programas.length || !centros.length) {
        return <div>Cargando datos...</div>;
    }

    return (
        <div>
            <h1>Fichas Odontológicas</h1>
            <form
                onSubmit={handleSubmit}
                className="fichas-form"
            >
                <input
                    name="fecha_control"
                    type="date"
                    value={form.fecha_control}
                    onChange={handleChange}
                    required
                    className="fichas-input-fecha"
                />
                <input
                    name="observacion"
                    placeholder="Observación"
                    value={form.observacion}
                    onChange={handleChange}
                    required
                    className="fichas-input-observacion"
                />
                <select
                    name="id_paciente"
                    value={form.id_paciente}
                    onChange={handleChange}
                    required
                    className="fichas-select-paciente"
                >
                    <option value="">Selecciona paciente</option>
                    {pacientes.map((p) => (
                        <option key={`paciente-${p.id_paciente}`} value={p.id_paciente}>
                            {`${p.rut}, ${p.nombre} ${p.apellido_paterno} ${p.apellido_materno}`}
                        </option>
                    ))}
                </select>
                <select
                    name="id_programa_salud_oral"
                    value={form.id_programa_salud_oral}
                    onChange={handleChange}
                    required
                    className="fichas-select-programa"
                >
                    <option value="">Selecciona programa salud oral</option>
                    {programas
                        .map((pr) => (
                            <option key={`programa-${pr.id_programa_salud_oral}`} value={pr.id_programa_salud_oral}>
                                {`${pr.codigo}, ${pr.nombre}`}
                            </option>
                        ))}
                </select>
                <select
                    name="id_centro_salud"
                    value={form.id_centro_salud}
                    onChange={handleChange}
                    required
                    className="fichas-select-centro"
                >
                    <option value="">Selecciona centro de salud</option>
                    {centros.map((c) => (
                        <option key={`centro-${c.id_centro_salud}`} value={c.id_centro_salud}>
                            {c.nombre}
                        </option>
                    ))}
                </select>
                <button type="submit" className="fichas-btn">
                    Agregar
                </button>
            </form>

            <table className="fichas-table">
                <thead>
                <tr>
                    <th className="fichas-th">ID</th>
                    <th className="fichas-th">Fecha Control</th>
                    <th className="fichas-th">Observación</th>
                    <th className="fichas-th">Paciente</th>
                    <th className="fichas-th">Programa Salud Oral</th>
                    <th className="fichas-th">Centro Salud</th>
                    <th className="fichas-th">Usuario Resp.</th>
                </tr>
                </thead>
                <tbody>
                {fichas.map((f) => {
                    const paciente = pacientes.find((p) => Number(p.id_paciente) === Number(f.id_paciente));
                    const programa = programas.find((pr) => Number(pr.id_programa_salud_oral) === Number(f.id_programa_salud_oral));
                    const centro = centros.find((c) => Number(c.id_centro_salud) === Number(f.id_centro_salud));
                    return (
                        <tr key={f.id_ficha_odontologica}>
                            <td className="fichas-td">{f.id_ficha_odontologica}</td>
                            <td className="fichas-td">{new Date(f.fecha_control).toLocaleDateString('es-CL')}</td>
                            <td className="fichas-td">{f.observacion}</td>
                            <td className="fichas-td">
                                {paciente
                                    ? `${paciente.nombre} ${paciente.apellido_paterno} ${paciente.apellido_materno}`
                                    : f.id_paciente}
                            </td>
                            <td className="fichas-td">{programa ? programa.nombre : f.id_programa_salud_oral}</td>
                            <td className="fichas-td">{centro ? centro.nombre : f.id_centro_salud}</td>
                            <td className="fichas-td">{user?.nombre ?? f.id_usuario_responsable}</td>
                        </tr>
                    );
                })}
                </tbody>
            </table>
        </div>
    );
}

// frontend/src/app/pages/fichas-odontologica/fichas-odontologica.component.ts

import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../../services/api.service';
import { FichasOdontologicaDataService } from '../../data-services/fichas-odontologica-data.service';
import { FichaOdontologica } from './fichas-odontologica.interfaces';

@Component({
  selector: 'app-fichas-odontologica',
  standalone: false,
  templateUrl: './fichas-odontologica.component.html',
  styleUrl: './fichas-odontologica.component.css'
})
export class FichasOdontologicaComponent implements OnInit {

  fichasOdontologicas: FichaOdontologica[] = [];
  loading = true;
  editingFicha: FichaOdontologica | null = null;
  showModal = false;

  constructor(
    private apiService: ApiService,
    private fichasOdontologicaDataService: FichasOdontologicaDataService
  ) { }

  ngOnInit(): void {
    this.loadAllData();
  }

  async loadAllData(): Promise<void> {
    try {
      await this.fichasOdontologicaDataService.loadStaticData();
      this.fichasOdontologicas = await this.apiService.getFichasOdonto();
      this.loading = false;
    } catch (error) {
      console.error('Error al cargar datos:', error);
      this.loading = false;
    }
  }

  openCreateModal(): void {
    this.editingFicha = null;
    this.showModal = true;
  }

  openEditModal(ficha: FichaOdontologica): void {
    this.editingFicha = ficha;
    this.showModal = true;
  }

  closeModal(): void {
    this.editingFicha = null;
    this.showModal = false;
  }

  async saveFicha(ficha: FichaOdontologica) {
    await this.apiService.createFichaOdonto(ficha);
    alert('Ficha odontológica creada correctamente');
    await this.loadAllData();
    this.closeModal();
  }

  async updateFicha(ficha: FichaOdontologica) {
    await this.apiService.updateFichaOdonto(ficha.id_ficha_odontologica, ficha);
    alert('Ficha odontológica actualizada correctamente');
    await this.loadAllData();
    this.closeModal();
  }

  getPacienteNombre(id_paciente: number): string {
    return this.fichasOdontologicaDataService.getPacienteNombre(id_paciente);
  }

  getProgramaNombre(id_programa: number): string {
    return this.fichasOdontologicaDataService.getProgramaNombre(id_programa);
  }

  getCentroNombre(id_centro: number): string {
    return this.fichasOdontologicaDataService.getCentroNombre(id_centro);
  }

  getUsuarioNombre(id_usuario: number): string {
    return this.fichasOdontologicaDataService.getUsuarioNombre(id_usuario);
  }

  formatFecha(dateString: string): string {
    return new Date(dateString).toLocaleDateString('es-CL');
  }
}

<div *ngIf="loading">Cargando datos...</div>

<div *ngIf="!loading" class="p-6">
    <div class="header-row" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
        <h1 class="page_header" style="margin: 0;">Fichas Odontológicas</h1>
        <button (click)="openCreateModal()" class="btn-crear">
            <span class="btn-text">Crear Ficha Odontológica</span>
        </button>
    </div>

    <app-ficha-odontologica-form [isOpen]="showModal" [ficha]="editingFicha" (onClose)="closeModal()" (onSave)="saveFicha($event)" (onUpdate)="updateFicha($event)"></app-ficha-odontologica-form>

    <table class="table-unified" *ngIf="fichasOdontologicas && fichasOdontologicas.length > 0">
        <thead>
            <tr>
                <th class="table-unified-th">Fecha Control</th>
                <th class="table-unified-th">Observación</th>
                <th class="table-unified-th">Paciente</th>
                <th class="table-unified-th">Programa Salud Oral</th>
                <th class="table-unified-th">Centro Salud</th>
                <th class="table-unified-th">Usuario Resp.</th>
                <th class="table-unified-th">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let ficha of fichasOdontologicas">
                <td class="table-unified-td">{{ formatFecha(ficha.fecha_control) }}</td>
                <td class="table-unified-td">{{ ficha.observacion }}</td>
                <td class="table-unified-td">{{ getPacienteNombre(ficha.id_paciente) }}</td>
                <td class="table-unified-td">{{ getProgramaNombre(ficha.id_programa_salud_oral) }}</td>
                <td class="table-unified-td">{{ getCentroNombre(ficha.id_centro_salud) }}</td>
                <td class="table-unified-td">{{ getUsuarioNombre(ficha.id_usuario_responsable) }}</td>
                <td class="table-unified-td">
                    <button (click)="openEditModal(ficha)">Editar</button>
                </td>
            </tr>
        </tbody>
    </table>

    <div *ngIf="fichasOdontologicas.length === 0" class="text-center py-8 text-gray-500">
        No hay fichas odontológicas registradas
    </div>
</div>
