// frontend/src/app/recetas/page.tsx
'use client';

import React, {ChangeEvent, FormEvent, useEffect, useState} from 'react';
import {apiService} from '@/services/ApiService';
import './styles.css';

// Interfaces
interface Paciente {
    id_paciente: number;
    nombre: string;
    apellido_paterno: string;
    apellido_materno: string;
    rut: string;
}

interface Usuario {
    id_usuario: number;
    nombre: string;
    apellido_paterno?: string;
    apellido_materno?: string;
}

interface Medicamento {
    id_medicamento: number;
    nombre: string;
    descripcion: string;
}

interface RecetaMedicamentoForm {
    id_medicamento: string;
    dosis_cantidad: string;
    dosis_unidad: string;
    frecuencia_horas: string;
    duracion_dias: string;
}

const UNIDADES_DOSIS = ['tableta(s)', 'ml', 'mg', 'gota(s)', 'cucharada(s)', 'capsula(s)'];

export default function RecetasPage() {
    const [pacientes, setPacientes] = useState<Paciente[]>([]);
    const [usuarios, setUsuarios] = useState<Usuario[]>([]);
    const [medicamentos, setMedicamentos] = useState<Medicamento[]>([]);
    const [recetas, setRecetas] = useState<any[]>([]);
    const [showModal, setShowModal] = useState(false);
    const [detalleReceta, setDetalleReceta] = useState<any[] | null>(null);
    const [showDetalle, setShowDetalle] = useState(false);
    const [detalleTitulo, setDetalleTitulo] = useState('');

    const [form, setForm] = useState({
        id_paciente: '',
        id_medico: '',
        indicacion: '',
        items: [] as RecetaMedicamentoForm[],
    });

    // Modal handlers
    const handleOpenModal = () => setShowModal(true);
    const handleCloseModal = () => setShowModal(false);

    useEffect(() => {
        apiService.getPacientes().then(data => setPacientes(data));
        apiService.getUsuarios().then(data => setUsuarios(data));
        apiService.getMedicamentos().then(data => setMedicamentos(data));
        apiService.getRecetas().then(data => setRecetas(data));
    }, []);

    const handleChange = (e: ChangeEvent<HTMLSelectElement | HTMLInputElement | HTMLTextAreaElement>) => {
        setForm({...form, [e.target.name]: e.target.value});
    };

    const handleItemChange = (
        idx: number,
        e: ChangeEvent<HTMLInputElement | HTMLSelectElement>
    ) => {
        const items = [...form.items];
        items[idx] = {...items[idx], [e.target.name]: e.target.value};
        setForm({...form, items});
    };

    const handleAddItem = () => {
        setForm({
            ...form,
            items: [
                ...form.items,
                {
                    id_medicamento: '',
                    dosis_cantidad: '',
                    dosis_unidad: '',
                    frecuencia_horas: '',
                    duracion_dias: '',
                },
            ],
        });
    };

    const handleRemoveItem = (idx: number) => {
        const items = [...form.items];
        items.splice(idx, 1);
        setForm({...form, items});
    };

    // Calcula la cantidad a despachar
    function calcularCantidadDespachada(
        dosis_cantidad: string,
        frecuencia_horas: string,
        duracion_dias: string,
        dosis_unidad: string
    ) {
        const dosisNum = parseFloat(dosis_cantidad || '1');
        const frecuenciaNum = parseFloat(frecuencia_horas || '1');
        const diasNum = parseInt(duracion_dias || '1', 10);

        const vecesPorDia = frecuenciaNum > 0 ? 24 / frecuenciaNum : 1;
        const total = Math.ceil(dosisNum * vecesPorDia * diasNum);
        return `${total} ${dosis_unidad}`;
    }

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        // 1. Crear receta
        const recetaPayload = {
            id_paciente: Number(form.id_paciente),
            id_medico: Number(form.id_medico),
            fecha_emision: new Date().toISOString().slice(0, 19).replace('T', ' '), // now()
            indicacion: form.indicacion,
        };
        const receta = await apiService.createReceta(recetaPayload);

        // 2. Crear ítems de receta y despachos
        for (const item of form.items) {
            const recetaMedPayload = {
                id_receta: receta.id_receta,
                id_medicamento: Number(item.id_medicamento),
                dosis: `${item.dosis_cantidad} ${item.dosis_unidad}`,
                frecuencia: `${item.frecuencia_horas} hora(s)`,
                duracion_dias: Number(item.duracion_dias),
            };
            const recetaMed = await apiService.createRecetaMedicamento(recetaMedPayload);

            // Despacho automático (now + 1 hora)
            const fecha_despacho = new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 19).replace('T', ' ');
            const cantidad_despachada = calcularCantidadDespachada(
                item.dosis_cantidad,
                item.frecuencia_horas,
                item.duracion_dias,
                item.dosis_unidad
            );
            await apiService.createDespachoMedicamento({
                id_receta_med: recetaMed.id_receta_medicamento,
                fecha_despacho,
                cantidad_despachada,
                id_farmacia: 1, // puedes ajustar según tu lógica
            });
        }

        setForm({
            id_paciente: '',
            id_medico: '',
            indicacion: '',
            items: [],
        });
        apiService.getRecetas().then(setRecetas);
        setShowModal(false);
        alert('Receta creada y despachos generados');
    };

    const handleVerDetalle = async (receta: any) => {
        const response = await apiService.getRecMedByReceta(receta.id_receta);
        const items = Array.isArray(response) ? response : [response];
        setDetalleReceta(items);
        setDetalleTitulo(`Detalle de receta #${receta.id_receta}`);
        setShowDetalle(true);
    };

    const handleCerrarDetalle = () => {
        setShowDetalle(false);
        setDetalleReceta(null);
        setDetalleTitulo('');
    };

    return (
        <div>
            <h1>Recetas</h1>
            <button onClick={handleOpenModal} className="recetas-btn-crear">
                Crear receta
            </button>
            {showModal && (
                <div className="recetas-modal-bg">
                    <div className="recetas-modal">
                        <button
                            onClick={handleCloseModal}
                            className="recetas-modal-close"
                            title="Cerrar"
                        >
                            ×
                        </button>
                        <h2 className="recetas-modal-title">Nueva Receta</h2>
                        <form onSubmit={handleSubmit} className="recetas-form">
                            <div className="recetas-form-row">
                                <div className="recetas-form-col">
                                    <label className="recetas-label">Paciente</label>
                                    <select
                                        name="id_paciente"
                                        value={form.id_paciente}
                                        onChange={handleChange}
                                        required
                                        className="recetas-select"
                                    >
                                        <option value="">Selecciona paciente</option>
                                        {pacientes.map((p) => (
                                            <option key={p.id_paciente} value={p.id_paciente}>
                                                {`${p.nombre} ${p.apellido_paterno ?? ''} ${p.apellido_materno ?? ''}`}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                                <div className="recetas-form-col">
                                    <label className="recetas-label">Médico</label>
                                    <select
                                        name="id_medico"
                                        value={form.id_medico}
                                        onChange={handleChange}
                                        required
                                        className="recetas-select"
                                    >
                                        <option value="">Selecciona médico</option>
                                        {usuarios.map((u) => (
                                            <option key={u.id_usuario} value={u.id_usuario}>
                                                {`${u.nombre} ${u.apellido_paterno ?? ''} ${u.apellido_materno ?? ''}`}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            </div>
                            <div>
                                <label className="recetas-label">Indicaciones generales</label>
                                <textarea
                                    name="indicacion"
                                    placeholder="Indicaciones generales"
                                    value={form.indicacion}
                                    onChange={handleChange}
                                    rows={2}
                                    className="recetas-textarea"
                                />
                            </div>
                            <div>
                                <h3 style={{margin: '0 0 0.5rem 0'}}>Medicamentos</h3>
                                <div className="recetas-medicamentos-list">
                                    {form.items.map((item, idx) => (
                                        <div
                                            key={idx}
                                            className="recetas-medicamento-item"
                                        >
                                            <select
                                                name="id_medicamento"
                                                value={item.id_medicamento}
                                                onChange={e => handleItemChange(idx, e)}
                                                required
                                                className="recetas-select"
                                            >
                                                <option value="">Medicamento</option>
                                                {medicamentos.map(m => (
                                                    <option key={m.id_medicamento} value={m.id_medicamento}>
                                                        {m.nombre}
                                                    </option>
                                                ))}
                                            </select>
                                            <input
                                                name="dosis_cantidad"
                                                type="number"
                                                min={1}
                                                placeholder="Dosis"
                                                value={item.dosis_cantidad}
                                                onChange={e => handleItemChange(idx, e)}
                                                required
                                                className="recetas-input"
                                            />
                                            <select
                                                name="dosis_unidad"
                                                value={item.dosis_unidad}
                                                onChange={e => handleItemChange(idx, e)}
                                                required
                                                className="recetas-select"
                                            >
                                                <option value="">Unidad</option>
                                                {UNIDADES_DOSIS.map(u => (
                                                    <option key={u} value={u}>{u}</option>
                                                ))}
                                            </select>
                                            <input
                                                name="frecuencia_horas"
                                                type="number"
                                                min={1}
                                                placeholder="Cada (hora)"
                                                value={item.frecuencia_horas}
                                                onChange={e => handleItemChange(idx, e)}
                                                required
                                                className="recetas-input"
                                            />
                                            <input
                                                name="duracion_dias"
                                                type="number"
                                                min={1}
                                                placeholder="Días"
                                                value={item.duracion_dias}
                                                onChange={e => handleItemChange(idx, e)}
                                                required
                                                className="recetas-input"
                                            />
                                            <button
                                                type="button"
                                                onClick={() => handleRemoveItem(idx)}
                                                className="recetas-medicamento-remove"
                                                title="Eliminar"
                                            >
                                                ×
                                            </button>
                                        </div>
                                    ))}
                                </div>
                                <button
                                    type="button"
                                    onClick={handleAddItem}
                                    className="recetas-medicamento-add"
                                >
                                    Agregar medicamento
                                </button>
                            </div>
                            <div className="recetas-form-actions">
                                <button
                                    type="submit"
                                    className="recetas-form-submit"
                                >
                                    Crear receta
                                </button>
                                <button
                                    type="button"
                                    onClick={handleCloseModal}
                                    className="recetas-form-cancel"
                                >
                                    Cancelar
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            <table className="recetas-table">
                <thead>
                <tr>
                    <th className="recetas-th">ID</th>
                    <th className="recetas-th">Paciente</th>
                    <th className="recetas-th">Médico</th>
                    <th className="recetas-th">Fecha Emisión</th>
                    <th className="recetas-th">Indicaciones</th>
                    <th className="recetas-th">Medicamentos</th>
                </tr>
                </thead>
                <tbody>
                {recetas.map((r: any) => (
                    <tr key={r.id_receta}>
                        <td className="recetas-td">{r.id_receta}</td>
                        <td className="recetas-td">
                            {
                                pacientes.find(p => p.id_paciente === r.id_paciente)
                                    ? `${pacientes.find(p => p.id_paciente === r.id_paciente)?.nombre} ${pacientes.find(p => p.id_paciente === r.id_paciente)?.apellido_paterno ?? ''} ${pacientes.find(p => p.id_paciente === r.id_paciente)?.apellido_materno ?? ''}`
                                    : ''
                            }
                        </td>
                        <td className="recetas-td">
                            {
                                usuarios.find(u => u.id_usuario === r.id_medico)
                                    ? `${usuarios.find(u => u.id_usuario === r.id_medico)?.nombre} ${usuarios.find(u => u.id_usuario === r.id_medico)?.apellido_paterno ?? ''} ${usuarios.find(u => u.id_usuario === r.id_medico)?.apellido_materno ?? ''}`
                                    : ''
                            }
                        </td>
                        <td className="recetas-td">{r.fecha_emision}</td>
                        <td className="recetas-td">{r.indicacion}</td>
                        <td className="recetas-td">
                            <button
                                className="recetas-verdetalle-btn"
                                onClick={() => handleVerDetalle(r)}
                            >
                                Ver detalle
                            </button>
                        </td>
                    </tr>
                ))}
                </tbody>
            </table>

            {/* Modal de detalle de receta */}
            {showDetalle && (
                <div className="recetas-detalle-modal-bg">
                    <div className="recetas-detalle-modal">
                        <button
                            onClick={handleCerrarDetalle}
                            className="recetas-detalle-close"
                            title="Cerrar"
                        >
                            ×
                        </button>
                        <h2 className="recetas-detalle-title">{detalleTitulo}</h2>
                        <table className="recetas-detalle-table">
                            <thead>
                            <tr>
                                <th className="recetas-detalle-th">Nombre</th>
                                <th className="recetas-detalle-th">Dosis</th>
                                <th className="recetas-detalle-th">Frecuencia</th>
                                <th className="recetas-detalle-th">Duración (días)</th>
                            </tr>
                            </thead>
                            <tbody>
                            {detalleReceta?.map((item, idx) => {
                                const med = medicamentos.find(m => m.id_medicamento === item.id_medicamento);
                                return (
                                    <tr key={idx}>
                                        <td className="recetas-detalle-td">{med ? med.nombre : item.id_medicamento}</td>
                                        <td className="recetas-detalle-td">{item.dosis}</td>
                                        <td className="recetas-detalle-td">{item.frecuencia}</td>
                                        <td className="recetas-detalle-td">{item.duracion_dias}</td>
                                    </tr>
                                );
                            })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
}

// frontend/src/app/recetas/recetas.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { RecetasDataService } from '../data-services/recetas-data.service';
import {
  Receta,
  RecetaMedicamento,
  RecetaMedicamentoForm
} from './recetas.interfaces';

// Interfaces para el componente

@Component({
  selector: 'app-recetas',
  standalone: false,
  templateUrl: './recetas.component.html',
  styleUrl: './recetas.component.css'
})
export class RecetasComponent implements OnInit {
  recetas: Receta[] = [];
  showModal = false;
  detalleReceta: RecetaMedicamento[] | null = null;
  showDetalle = false;
  detalleTitulo = '';
  loading = true;

  form = {
    id_paciente: '',
    id_medico: '',
    indicacion: '',
    items: [] as RecetaMedicamentoForm[],
  };

  UNIDADES_DOSIS = ['tableta(s)', 'ml', 'mg', 'gota(s)', 'cucharada(s)', 'capsula(s)'];

  constructor(
    private apiService: ApiService,
    private recetasDataService: RecetasDataService
  ) { }

  ngOnInit(): void {
    this.loadAllData();
  }

  async loadAllData(): Promise<void> {
    try {
      // ✅ OPTIMIZACIÓN: Cargar datos principales Y estáticos EN PARALELO
      const [recetasData] = await Promise.all([
        this.apiService.getRecetas(),
        this.recetasDataService.loadStaticData() // Se ejecuta en paralelo, no bloquea
      ]);

      // Mostrar las recetas inmediatamente
      this.recetas = recetasData;
      this.loading = false;
    } catch (error) {
      console.error('Error al cargar datos:', error);
      this.loading = false;
    }
  }

  // Métodos para obtener nombres
  getPacienteNombre(id_paciente: number): string {
    return this.recetasDataService.getPacienteNombre(id_paciente);
  }

  getUsuarioNombre(id_usuario: number): string {
    return this.recetasDataService.getMedicoNombre(id_usuario);
  }

  getMedicoNombre(id_medico: number): string {
    return this.recetasDataService.getMedicoNombre(id_medico);
  }

  getMedicamentoNombre(id_medicamento: number): string {
    return this.recetasDataService.getMedicamentoNombre(id_medicamento);
  }

  // Métodos para formularios
  getPacientes() {
    return this.recetasDataService.getPacientesForSelect();
  }

  getUsuarios() {
    return this.recetasDataService.getUsuariosForSelect();
  }

  getMedicamentos() {
    return this.recetasDataService.getMedicamentosForSelect();
  }

  // Modal handlers
  handleOpenModal(): void {
    this.showModal = true;
  }

  handleCloseModal(): void {
    this.showModal = false;
  }

  handleChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;
    this.form = { ...this.form, [target.name]: target.value };
  }

  handleItemChange(idx: number, event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement;
    const items = [...this.form.items];
    items[idx] = { ...items[idx], [target.name]: target.value };
    this.form = { ...this.form, items };
  }

  handleAddItem(): void {
    this.form = {
      ...this.form,
      items: [
        ...this.form.items,
        {
          id_medicamento: '',
          dosis_cantidad: '',
          dosis_unidad: '',
          frecuencia_horas: '',
          duracion_dias: '',
        },
      ],
    };
  }

  handleRemoveItem(idx: number): void {
    const items = [...this.form.items];
    items.splice(idx, 1);
    this.form = { ...this.form, items };
  }

  // Calcula la cantidad a despachar
  calcularCantidadDespachada(
    dosis_cantidad: string,
    frecuencia_horas: string,
    duracion_dias: string,
    dosis_unidad: string
  ): string {
    const dosisNum = parseFloat(dosis_cantidad || '1');
    const frecuenciaNum = parseFloat(frecuencia_horas || '1');
    const diasNum = parseInt(duracion_dias || '1', 10);

    const vecesPorDia = frecuenciaNum > 0 ? 24 / frecuenciaNum : 1;
    const total = Math.ceil(dosisNum * vecesPorDia * diasNum);
    return `${total} ${dosis_unidad}`;
  }

  async handleSubmit(event: Event): Promise<void> {
    event.preventDefault();
    try {
      // 1. Crear receta
      const recetaPayload = {
        id_paciente: Number(this.form.id_paciente),
        id_medico: Number(this.form.id_medico),
        fecha_emision: new Date().toISOString().slice(0, 19).replace('T', ' '), // now()
        indicacion: this.form.indicacion,
      };
      const receta = await this.apiService.createReceta(recetaPayload);

      // 2. Crear ítems de receta y despachos
      for (const item of this.form.items) {
        const recetaMedPayload = {
          id_receta: receta.id_receta,
          id_medicamento: Number(item.id_medicamento),
          dosis: `${item.dosis_cantidad} ${item.dosis_unidad}`,
          frecuencia: `${item.frecuencia_horas} hora(s)`,
          duracion_dias: Number(item.duracion_dias),
        };
        const recetaMed = await this.apiService.createRecetaMedicamento(recetaMedPayload);

        // Despacho automático (now + 1 hora)
        const fecha_despacho = new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 19).replace('T', ' ');
        const cantidad_despachada = this.calcularCantidadDespachada(
          item.dosis_cantidad,
          item.frecuencia_horas,
          item.duracion_dias,
          item.dosis_unidad
        );
        await this.apiService.createDespachoMedicamento({
          id_receta_med: recetaMed.id_receta_medicamento,
          fecha_despacho,
          cantidad_despachada,
          id_farmacia: 1, // puedes ajustar según tu lógica
        });
      }

      this.form = {
        id_paciente: '',
        id_medico: '',
        indicacion: '',
        items: [],
      };
      this.recetas = await this.apiService.getRecetas();
      this.showModal = false;
      alert('Receta creada y despachos generados');
    } catch (error) {
      alert('Error al crear receta');
      console.error('Error:', error);
    }
  }

  async handleVerDetalle(receta: Receta): Promise<void> {
    try {
      const response = await this.apiService.getRecMedByReceta(receta.id_receta);
      const items = Array.isArray(response) ? response : [response];
      this.detalleReceta = items;
      this.detalleTitulo = `Detalle de receta #${receta.id_receta}`;
      this.showDetalle = true;
    } catch (error) {
      console.error('Error al cargar detalle:', error);
    }
  }

  handleCerrarDetalle(): void {
    this.showDetalle = false;
    this.detalleReceta = null;
    this.detalleTitulo = '';
  }

  formatFecha(fecha: string): string {
    return new Date(fecha).toLocaleDateString('es-CL');
  }
}

<div *ngIf="loading">Cargando datos...</div>

<div *ngIf="!loading" class="p-6">
    <h1 class="page_header">Recetas</h1>
    <button (click)=" handleOpenModal()" class="recetas-btn-crear">
        Crear receta
    </button>

    <!-- Modal de creación -->
    <div *ngIf="showModal" class="recetas-modal-bg">
        <div class="recetas-modal">
            <button (click)="handleCloseModal()" class="recetas-modal-close" title="Cerrar">
                ×
            </button>
            <h2 class="recetas-modal-title">Nueva Receta</h2>
            <form (ngSubmit)="handleSubmit($event)" class="recetas-form">
                <div class="recetas-form-row">
                    <div class="recetas-form-col">
                        <label class="recetas-label">Paciente</label>
                        <select name="id_paciente" [value]="form.id_paciente" (change)="handleChange($event)" required
                            class="recetas-select">
                            <option value="">Selecciona paciente</option>
                            <option *ngFor="let p of getPacientes()" [value]="p.id">
                                {{p.nombre}}
                            </option>
                        </select>
                    </div>
                    <div class="recetas-form-col">
                        <label class="recetas-label">Médico</label>
                        <select name="id_medico" [value]="form.id_medico" (change)="handleChange($event)" required
                            class="recetas-select">
                            <option value="">Selecciona médico</option>
                            <option *ngFor="let u of getUsuarios()" [value]="u.id">
                                {{u.nombre}}
                            </option>
                        </select>
                    </div>
                </div>
                <div>
                    <label class="recetas-label">Indicaciones generales</label>
                    <textarea name="indicacion" placeholder="Indicaciones generales" [value]="form.indicacion"
                        (input)="handleChange($event)" rows="2" class="recetas-textarea">
                    </textarea>
                </div>
                <div>
                    <h3 style="margin: 0 0 0.5rem 0">Medicamentos</h3>
                    <div class="recetas-medicamentos-list">
                        <div *ngFor="let item of form.items; let idx = index" class="recetas-medicamento-item">
                            <select name="id_medicamento" [value]="item.id_medicamento"
                                (change)="handleItemChange(idx, $event)" required class="recetas-select">
                                <option value="">Medicamento</option>
                                <option *ngFor="let m of getMedicamentos()" [value]="m.id">
                                    {{m.nombre}}
                                </option>
                            </select>
                            <input name="dosis_cantidad" type="number" min="1" placeholder="Dosis"
                                [value]="item.dosis_cantidad" (input)="handleItemChange(idx, $event)" required
                                class="recetas-input" />
                            <select name="dosis_unidad" [value]="item.dosis_unidad"
                                (change)="handleItemChange(idx, $event)" required class="recetas-select">
                                <option value="">Unidad</option>
                                <option *ngFor="let u of UNIDADES_DOSIS" [value]="u">{{u}}</option>
                            </select>
                            <input name="frecuencia_horas" type="number" min="1" placeholder="Cada (hora)"
                                [value]="item.frecuencia_horas" (input)="handleItemChange(idx, $event)" required
                                class="recetas-input" />
                            <input name="duracion_dias" type="number" min="1" placeholder="Días"
                                [value]="item.duracion_dias" (input)="handleItemChange(idx, $event)" required
                                class="recetas-input" />
                            <button type="button" (click)="handleRemoveItem(idx)" class="recetas-medicamento-remove"
                                title="Eliminar">
                                ×
                            </button>
                        </div>
                    </div>
                    <button type="button" (click)="handleAddItem()" class="recetas-medicamento-add">
                        Agregar medicamento
                    </button>
                </div>
                <div class="recetas-form-actions">
                    <button type="submit" class="recetas-form-submit">
                        Crear receta
                    </button>
                    <button type="button" (click)="handleCloseModal()" class="recetas-form-cancel">
                        Cancelar
                    </button>
                </div>
            </form>
        </div>
    </div>

    <table class="table-unified">
        <thead>
            <tr>
                <th class="table-unified-th">ID</th>
                <th class="table-unified-th">Paciente</th>
                <th class="table-unified-th">Médico</th>
                <th class="table-unified-th">Fecha Emisión</th>
                <th class="table-unified-th">Indicaciones</th>
                <th class="table-unified-th">Medicamentos</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let r of recetas">
                <td class="table-unified-td">{{r.id_receta}}</td>
                <td class="table-unified-td">{{getPacienteNombre(r.id_paciente)}}</td>
                <td class="table-unified-td">{{getMedicoNombre(r.id_medico)}}</td>
                <td class="table-unified-td">{{formatFecha(r.fecha_emision)}}</td>
                <td class="table-unified-td">{{r.indicacion}}</td>
                <td class="table-unified-td">
                    <button class="recetas-verdetalle-btn" (click)="handleVerDetalle(r)">
                        Ver detalle
                    </button>
                </td>
            </tr>
        </tbody>
    </table>

    <!-- Modal de detalle de receta -->
    <div *ngIf="showDetalle" class="recetas-detalle-modal-bg">
        <div class="recetas-detalle-modal">
            <button (click)="handleCerrarDetalle()" class="recetas-detalle-close" title="Cerrar">
                ×
            </button>
            <h2 class="recetas-detalle-title">{{detalleTitulo}}</h2>
            <table class="table-unified">
                <thead>
                    <tr>
                        <th class="table-unified-th">Nombre</th>
                        <th class="table-unified-th">Dosis</th>
                        <th class="table-unified-th">Frecuencia</th>
                        <th class="table-unified-th">Duración (días)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let item of detalleReceta; let idx = index">
                        <td class="table-unified-td">{{getMedicamentoNombre(item.id_medicamento)}}</td>
                        <td class="table-unified-td">{{item.dosis}}</td>
                        <td class="table-unified-td">{{item.frecuencia}}</td>
                        <td class="table-unified-td">{{item.duracion_dias}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
